foodList/urls.py
from django.urls import path
from . import views

app_name='foodList'
urlpatterns = [
    path('', views.index, name="index"),
    path('breadFruitPie/', views.breadFruitPie, name="breadFruitPie"),
    path('beefCutlet/', views.beefCutlet, name="beefCutlet"),
    path('basilPestoQuinoa/', views.basilPestoQuinoa, name="basilPestoQuinoa"),
    path('carrotSticksWithDip/', views.carrotSticksWithDip, name="carrotSticksWithDip"),
    path('chocolateMilkShake/', views.chocolateMilkShake, name="chocolateMilkShake"),
    path('doubleVeganPizzaWithSoyMilk/', views.doubleVeganPizzaWithSoyMilk, name="doubleVeganPizzaWithSoyMilk"),
    path('lentilNutTacos/', views.lentilNutTacos, name="lentilNutTacos"),
    path('mushroomFriedRice/', views.mushroomFriedRice, name="mushroomFriedRice"),
    path('peanutRaisinOatmeal/', views.peanutRaisinOatmeal, name="peanutRaisinOatmeal"),
    path('penneArabiataWithSoyMilk/', views.penneArabiataWithSoyMilk, name="penneArabiataWithSoyMilk"),
    path('pumpkinPie/', views.pumpkinPie, name="pumpkinPie"),
    path('soyMilk/', views.soyMilk, name="soyMilk"),
    path('veganLasagnaRolls/', views.veganLasagnaRolls, name="veganLasagnaRolls"),
    path('veganPizzaWithSoyMilk/', views.veganPizzaWithSoyMilk, name="veganPizzaWithSoyMilk"),
    path('vegetableMeat/', views.vegetableMeat, name="vegetableMeat"),
    path('porkChopWithMashedPotatoes/', views.porkChopWithMashedPotatoes, name="porkChopWithMashedPotatoes"),
    path('cerealWithFruit/', views.cerealWithFruit, name="cerealWithFruit"),
    path('tunaCucumberWrap/', views.tunaCucumberWrap, name="tunaCucumberWrap"),
    path('scrambledEggs/', views.scrambledEggs, name="scrambledEggs"),
    path('bananaBread/', views.bananaBread, name="bananaBread"),
    path('caesarSalad/', views.caesarSalad, name="caesarSalad"),
    path('californiaRollSushi/', views.californiaRollSushi, name="californiaRollSushi"),
    path('greenSaladWithHoneyLemonChicken/', views.greenSaladWithHoneyLemonChicken, name="greenSaladWithHoneyLemonChicken"),
]

spoonfulofgoodness/urls.py
from django.contrib import admin
from django.urls import  path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('foodList/', include('foodList.urls')),
    path('foodRecommendation/', include('foodRecommendation.urls')),
]

foodList/models.py
from django.db import models

class Recipe(models.Model):
    recipeName = models.CharField(max_length=50)
    recipeCalories = models.IntegerField(default=0)

    pork = models.BooleanField(default=False)
    alcohol = models.BooleanField(default=False)
    gluten = models.BooleanField(default=False)
    lactose = models.BooleanField(default=False)
    egg = models.BooleanField(default=False)
    meat = models.BooleanField(default=False)
    vegan = models.BooleanField(default=False)
    fish = models.BooleanField(default=False)
    containsMilk = models.BooleanField(default=False)
    containsMilkSubstitute = models.BooleanField(default=False)

    def __str__(self):
        return self.recipeName

foodList/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'foodList/templates/index.html', {})

def breadFruitPie(request):
    return render(request, 'foodList/templates/breadFruitPie.html', {})

def basilPestoQuinoa(request):
    return render(request, 'foodList/templates/basilPestoQuinoa.html', {})

def beefCutlet(request):
    return render(request, 'foodList/templates/beefCutlet.html', {})

def carrotSticksWithDip(request):
    return render(request, 'foodList/templates/carrotSticksWithDip.html', {})

def chocolateMilkShake(request):
    return render(request, 'foodList/templates/chocolateMilkShake.html', {})

def doubleVeganPizzaWithSoyMilk(request):
    return render(request, 'foodList/templates/doubleVeganPizzaWithSoyMilk.html', {})

def lentilNutTacos(request):
    return render(request, 'foodList/templates/lentilNutTacos.html', {})

def mushroomFriedRice(request):
    return render(request, 'foodList/templates/mushroomFriedRice.html', {})

def peanutRaisinOatmeal(request):
    return render(request, 'foodList/templates/peanutRaisinOatmeal.html', {})

def penneArabiataWithSoyMilk(request):
    return render(request, 'foodList/templates/penneArabiataWithSoyMilk.html', {})

def pumpkinPie(request):
    return render(request, 'foodList/templates/pumpkinPie.html', {})

def soyMilk(request):
    return render(request, 'foodList/templates/soyMilk.html', {})

def veganLasagnaRolls(request):
    return render(request, 'foodList/templates/veganLasagnaRolls.html', {})

def veganPizzaWithSoyMilk(request):
    return render(request, 'foodList/templates/veganPizzaWithSoyMilk.html', {})

def vegetableMeat(request):
    return render(request, 'foodList/templates/vegetableMeat.html', {})

def porkChopWithMashedPotatoes(request):
    return render(request, 'foodList/templates/porkChopWithMashedPotatoes.html', {})
    

def cerealWithFruit(request):
    return render(request, 'foodList/templates/cerealWithFruit.html', {})
    

def tunaCucumberWrap(request):
    return render(request, 'foodList/templates/tunaCucumberWrap.html', {})
    
def honeyLemonChicken(request):
    return render(request, 'foodList/templates/honeyLemonChicken.html', {})
    

def scrambledEggs(request):
    return render(request, 'foodList/templates/scrambledEggs.html', {})
    

def bananaBread(request):
    return render(request, 'foodList/templates/bananaBread.html', {})
    

def caesarSalad(request):
    return render(request, 'foodList/templates/caesarSalad.html', {})
    

def californiaRollSushi(request):
    return render(request, 'foodList/templates/californiaRollSushi.html', {})
    

def greenSaladWithHoneyLemonChicken(request):
    return render(request, 'foodList/templates/greenSaladWithHoneyLemonChicken.html', {})
    

foodList/templates/beefCutlet.html
{% extends "spoonfulofgoodness/layout/base.html" %}
{% load static %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}" type="text/css">
{% endblock %}
{% block content %}
<!-- Receipe Slider -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="receipe-slider owl-carousel">
                <img src="https://drive.google.com/uc?id=1IGQpnjmb480WZxp7Fw27Sfz97dHYaP9k" alt="">
                <img src="https://drive.google.com/uc?id=1IGQpnjmb480WZxp7Fw27Sfz97dHYaP9k" alt="">
                <img src="https://drive.google.com/uc?id=1IGQpnjmb480WZxp7Fw27Sfz97dHYaP9k" alt="">
            </div>
        </div>
    </div>
</div>
<br><br>
<!-- Receipe Content Area -->
<div class="receipe-content-area">
    <div class="container">

        <div class="row">
            <div class="col-12 col-md-8">
                <div class="receipe-headline my-5">
                    <span>April 05, 2018</span>
                    <h2>Beef Cutlet</h2>
                    <div class="receipe-duration">
                        <h6>Time: 50 mins</h6>
                        <h6>Servings: 3 plates</h6>
                        <h6>Calories: 300 KCal</h6>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="receipe-ratings text-right my-5">
                    <div class="ratings">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>
                    <a href="#" class="primary-btn header-btn text-uppercase">No Pork</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-8">
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>01.</h4>
                    <p>Prepare the beef cutlets first. Using a cheese grater, grate the onion into a large bowl. You can also use a food processor. To the bowl, add the ground beef, egg, and season with salt, pepper and fresh dill. Soak the bread in a bowl of water and squeeze out a bit water if too much is absorbed; I like to use a 6-inch piece of baguette.</p>
                </div>
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>02.</h4>
                    <p>Break the baguette into small pieces and add to the bowl. Using your hands, mix all the ingredients together until a uniform mixture forms. Use a measuring scoop (mine was 3 tablespoons) to portion the mixture into cutlet sized portions. Place the panko bread crumbs into a small bow. Press each cutlet into a flat oval shape, then drop into the bread crumbs, coating well all over.
                        </p>
                </div>
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>03.</h4>
                    <p>Preheat a large frying pan with a few tablespoons of olive oil over medium heat. Add the cutlets to the pan, spacing them out evenly. Avoid over-crowding the pan; cook the cutlets in batches. Fry the cutlets 4 to 6 minutes on each side, until golden brown. Make sure cutlets cook all the way through; check with a meat thermometer if need - it needs to reach 160F. Remove the cutlets onto a tray lined with paper towels to absorb any excess oil; keep warm until ready to serve.</p>
                </div>
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>04.</h4>
                    <p>Next, prepare the mushroom gravy. Melt the butter in a large saute pan, along with a bit of olive oil, over medium heat. Add the mushrooms and saute for 4 to 5 minutes, until the mushrooms are nicely browned. Season the mushrooms with a bit of salt once they're browned, then remove them from the pan into a large bowl.</p>
                </div>
            </div>

            <!-- Ingredients -->
            <div class="col-12 col-lg-4">
                <div class="ingredients">
                    <h4>Ingredients</h4>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                        <label class="custom-control-label" for="customCheck1">1 pound ground beef</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck2">
                        <label class="custom-control-label" for="customCheck2">1 large onion</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck3">
                        <label class="custom-control-label" for="customCheck3">1 large egg</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck4">
                        <label class="custom-control-label" for="customCheck4">1 tablespoon fresh dill</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck5">
                        <label class="custom-control-label" for="customCheck5">2 yogurt containers unbleached white flour</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck6">
                        <label class="custom-control-label" for="customCheck6">1.5 yogurt containers milk</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck7">
                        <label class="custom-control-label" for="customCheck7">1/4 tsp cinnamon</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck8">
                        <label class="custom-control-label" for="customCheck8">1 cup fresh blueberries </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

foodList/templates/caesarSalad.html
{% extends "spoonfulofgoodness/layout/base.html" %}
{% load static %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}" type="text/css">
{% endblock %}
{% block content %}
<!-- Receipe Slider -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="receipe-slider owl-carousel">
                <img src="https://drive.google.com/uc?id=1hibve4enni0FaCFf1FYkvb7bq8GW7OBl" alt="">
                <img src="https://drive.google.com/uc?id=1uGwdmhRULQGPWB5Lrr-J926yQIXQp4TQ" alt="">
                <img src="https://drive.google.com/uc?id=1IGQpnjmb480WZxp7Fw27Sfz97dHYaP9k" alt="">
            </div>
        </div>
    </div>
</div>
<br><br>
<!-- Receipe Content Area -->
<div class="receipe-content-area">
    <div class="container">

        <div class="row">
            <div class="col-12 col-md-8">
                <div class="receipe-headline my-5">
                    <span>April 05, 2018</span>
                    <h2>Caesar Salad</h2>
                    <div class="receipe-duration">
                        <h6>Time: 50 mins</h6>
                        <h6>Servings: 3 plates</h6>
                        <h6>Calories: 230 KCal</h6>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4">
                <div class="receipe-ratings text-right my-5">
                    <div class="ratings">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>
                    <a href="#" class="primary-btn header-btn text-uppercase">No Pork</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-8">
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>01.</h4>
                    <p>1.	Mince 3 cloves of garlic, and combine in a small bowl with mayonnaise, anchovies, 2 tablespoons of the Parmesan cheese, Worcestershire sauce, mustard, and lemon juice. Season to taste with salt and black pepper. Refrigerate until ready to use.</p>
                </div>
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>02.</h4>
                    <p>2.	Heat oil in a large skillet over medium heat. Cut the remaining 3 cloves of garlic into quarters, and add to hot oil. Cook and stir until brown, and then remove garlic from pan. Add bread cubes to the hot oil. Cook, turning frequently, until lightly browned. Remove bread cubes from oil, and season with salt and pepper.</p>
                </div>
                <!-- Single Preparation Step -->
                <div class="single-preparation-step d-flex">
                    <h4>03.</h4>
                    <p>3.	Place lettuce in a large bowl. Toss with dressing, remaining Parmesan cheese, and seasoned bread cubes </p>
                </div>
            </div>

            <!-- Ingredients -->
            <div class="col-12 col-lg-4">
                <div class="ingredients">
                    <h4>Ingredients</h4>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                        <label class="custom-control-label" for="customCheck1">4 Tbsp (57 gr) butter</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck2">
                        <label class="custom-control-label" for="customCheck2">2 large eggs</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck3">
                        <label class="custom-control-label" for="customCheck3">2 yogurt containers granulated sugar</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck4">
                        <label class="custom-control-label" for="customCheck4">1 vanilla or plain yogurt, 170g container</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck5">
                        <label class="custom-control-label" for="customCheck5">2 yogurt containers unbleached white flour</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck6">
                        <label class="custom-control-label" for="customCheck6">1.5 yogurt containers milk</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck7">
                        <label class="custom-control-label" for="customCheck7">1/4 tsp cinnamon</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck8">
                        <label class="custom-control-label" for="customCheck8">1 cup fresh blueberries </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

foodList/templates/index.html
{% extends "spoonfulofgoodness/layout/base.html" %}
{% load static %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}" type="text/css">
{% endblock %}

{% block content %}

<!-- Start top-dish Area -->
<section class="top-dish-area section-gap one-section" id="dish">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-60 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10">Our Top Rated Dishes</h1>
                    <p>Who are in extremely love with eco friendly system.</p>
                </div>
            </div>
        </div>						
        <div class="row d-flex justify-content-center">
            
            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:breadFruitPie'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://drive.google.com/uc?id=1Pj9_6CpsebtLNMnUvlX_UA7Cc8521QYh" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Bread Fruit Pie</h4>
            </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            
            </div>
            

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:beefCutlet'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://drive.google.com/uc?id=1hibve4enni0FaCFf1FYkvb7bq8GW7OBl" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Beef Cutlet</h4>
            </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>
            
            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:vegetableMeat'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://drive.google.com/uc?id=1uGwdmhRULQGPWB5Lrr-J926yQIXQp4TQ" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Vegetable Meat</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>
            
            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:californiaRollSushi'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://natashaskitchen.com/wp-content/uploads/2013/10/Sushi-Rice-California-Rolls-Recipe-2-2.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">California Roll Sushi</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:basilPestoQuinoa'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://veggiechick.com/wp-content/uploads/2016/12/Basil-Pesto-Quinoa_FEATURED.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Basil Pesto Quinoa</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:carrotSticksWithDip'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://www.vegan.io/attachments/5f1842166bf8f74d30ea65a5d03721d2bc1fb4a7/store/fill/975/1463/South/5f3ba67bcc6d1ba9f2c9499f44746cd2e2ef3d521bea625d144fe4b071ca/hummus-with-carrot-sticks.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Carrot Sticks With Dip</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:chocolateMilkShake'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://images-gmi-pmc.edge-generalmills.com/2a612714-ee3e-4198-89fd-3f80215c0ef6.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Chocolate Milkshake</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:doubleVeganPizzaWithSoyMilk'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://veganhuggs.com/wp-content/uploads/2017/10/vegan-pizza-recipe-3.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Double Vegan Pizza With Soy Milk</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:lentilNutTacos'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://veggiechick.com/wp-content/uploads/2019/02/Lentil-Nut-Tacos-with-Cashew-Avocado-2-731x1024.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Lentil Nut Tacos</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:mushroomFriedRice'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://www.whiskaffair.com/wp-content/uploads/2017/05/Mushroom-Fried-Rice-4-1-500x500.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Mushroom Fried Rice</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:peanutRaisinOatmeal'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="http://breakfastdramaqueen.com/wp-content/uploads/2015/05/CinnamonRaisinPeanutButter1s.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Peanut Raisin Oatmeal</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:penneArabiataWithSoyMilk'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://tastesbetterfromscratch.com/wp-content/uploads/2016/10/Penne-Arrabbiata-2.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Penne Arabiata With Soy Milk</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:pumpkinPie'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://i0.wp.com/www.livewellbakeoften.com/wp-content/uploads/2016/11/Homemade-Pumpkin-Pie-1-2.jpg?resize=1360%2C2040&ssl=1" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Pumpkin Pie</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:veganLasagnaRolls'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://www.karissasvegankitchen.com/wp-content/uploads/2018/08/vegan-lasagna-hi-res-6b.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Vegan Lasagna Rolls</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:soyMilk'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://cdn.ventmere.com/ventray/uploads/2017-06/soy-milk_Skjdk4mfW.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Soy Milk</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>

            <div class="single-dish col-lg-4">
                <a href="{% url 'foodList:veganPizzaWithSoyMilk'%}">
                <div class="thumb">
                    <img class="img-fluid"  src="https://veganhuggs.com/wp-content/uploads/2017/10/vegan-pizza-recipe-3.jpg" alt="" style="width:300px;height:160px;">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Vegan Pizza With Soy Milk</h4>
                </a>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>
        </div>
    </div>
</div>	
</section>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>

<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<!-- End top-dish Area -->


{% endblock %}