foodList/urls.py
from django.urls import path
from . import views

app_name='foodList'
urlpatterns = [
    path('', views.index, name="index"),
    path('breadFruitPie/', views.breadFruitPie, name="breadFruitPie"),
    path('beefCutlet/', views.beefCutlet, name="beefCutlet"),
    path('basilPestoQuinoa/', views.basilPestoQuinoa, name="basilPestoQuinoa"),
    path('carrotSticksWithDip/', views.carrotSticksWithDip, name="carrotSticksWithDip"),
    path('chocolateMilkShake/', views.chocolateMilkShake, name="chocolateMilkShake"),
    path('doubleVeganPizzaWithSoyMilk/', views.doubleVeganPizzaWithSoyMilk, name="doubleVeganPizzaWithSoyMilk"),
    path('lentilNutTacos/', views.lentilNutTacos, name="lentilNutTacos"),
    path('mushroomFriedRice/', views.mushroomFriedRice, name="mushroomFriedRice"),
    path('peanutRaisinOatmeal/', views.peanutRaisinOatmeal, name="peanutRaisinOatmeal"),
    path('penneArabiataWithSoyMilk/', views.penneArabiataWithSoyMilk, name="penneArabiataWithSoyMilk"),
    path('pumpkinPie/', views.pumpkinPie, name="pumpkinPie"),
    path('soyMilk/', views.soyMilk, name="soyMilk"),
    path('veganLasagnaRolls/', views.veganLasagnaRolls, name="veganLasagnaRolls"),
    path('veganPizzaWithSoyMilk/', views.veganPizzaWithSoyMilk, name="veganPizzaWithSoyMilk"),
    path('vegetableMeat/', views.vegetableMeat, name="vegetableMeat"),
    path('porkChopWithMashedPotatoes/', views.porkChopWithMashedPotatoes, name="porkChopWithMashedPotatoes"),
    path('cerealWithFruit/', views.cerealWithFruit, name="cerealWithFruit"),
    path('tunaCucumberWrap/', views.tunaCucumberWrap, name="tunaCucumberWrap"),
    path('scrambledEggs/', views.scrambledEggs, name="scrambledEggs"),
    path('bananaBread/', views.bananaBread, name="bananaBread"),
    path('caesarSalad/', views.caesarSalad, name="caesarSalad"),
    path('californiaRollSushi/', views.californiaRollSushi, name="californiaRollSushi"),
    path('greenSaladWithHoneyLemonChicken/', views.greenSaladWithHoneyLemonChicken, name="greenSaladWithHoneyLemonChicken"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('', views.index, name="index"),
    path('home/', views.home, name="home"),
    path('submit-constraints/', views.submit_constraints, name="submit-constraints"),
]

spoonfulofgoodness/urls.py
from django.contrib import admin
from django.urls import  path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('foodList/', include('foodList.urls')),
    path('foodRecommendation/', include('foodRecommendation.urls')),
]

templates/spoonfulofgoodness/partials/footer.html
{% load staticfiles %}
{% load static %}
<div class="container one-section" id="contact">
					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h4 class="text-white">About Us</h4>
								<p>
									Intelligence system project that will give people diet advice while getting constrained by people's different condition
								</p>
							</div>
						</div>
						<div class="col-lg-4  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h4 class="text-white">Contact Us</h4>
								<p>
									Feel free to contact us
								</p>
								<p class="number">
									012-6532-568-9746 <br>
									012-6532-569-9748
								</p>
							</div>
						</div>						
						<div class="col-lg-5  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h4 class="text-white">Newsletter</h4>
								<p>You can trust us. we only send  offers, not a single spam.</p>
								<div class="d-flex flex-row" id="mc_embed_signup">


									  <form class="navbar-form" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get">
									    <div class="input-group add-on">
									      	<input class="form-control" name="EMAIL" placeholder="Email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email address'" required="" type="email">
											<div style="position: absolute; left: -5000px;">
												<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
											</div>
									      <div class="input-group-btn">
									        <button class="genric-btn"><span class="lnr lnr-arrow-right"></span></button>
									      </div>
									    </div>
									      <div class="info mt-20"></div>									    
									  </form>

								</div>
							</div>
						</div>						
					</div>
					<div class="footer-bottom d-flex justify-content-between align-items-center flex-wrap">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            <p class="footer-text m-0">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>

templates/spoonfulofgoodness/partials/header.html
<!-- templates/partials/header.html -->
{% load staticfiles %}
{% load static %}
<div class="container">
		<div class="row align-items-center justify-content-between d-flex">
				<div id="logo">
						<a href="{% url 'homepage:index' %}"><img src="{% static 'img/spoonful-logo.png' %}" alt="" title="" style="max-width: 2rem;" /></a>
				</div>
				<nav id="nav-menu-container">
						<ul class="nav-menu">
								<li class="menu-active"><a href="{% url 'homepage:index' %}">Home</a></li>
								<li><a href="#dish">Dish</a></li>
								<li><a href="#planner">Planner</a></li>
								<li><a href="#contact">Contact</a></li>
								<li class="menu-has-children"><a href="">Pages</a>
										<ul>
												<li><a href="{% url 'foodList:index'%}">List of Menu</a></li>
										</ul>
								</li>
						</ul>
				</nav><!-- #nav-menu-container -->		    		
		</div>
</div>