foodList/urls.py
from django.urls import path
from . import views

app_name='foodList'
urlpatterns = [
    path('', views.index, name="index"),
    path('breadFruitPie/', views.breadFruitPie, name="breadFruitPie"),
    path('beefCutlet/', views.beefCutlet, name="beefCutlet"),
    path('basilPestoQuinoa/', views.basilPestoQuinoa, name="basilPestoQuinoa"),
    path('carrotSticksWithDip/', views.carrotSticksWithDip, name="carrotSticksWithDip"),
    path('chocolateMilkShake/', views.chocolateMilkShake, name="chocolateMilkShake"),
    path('doubleVeganPizzaWithSoyMilk/', views.doubleVeganPizzaWithSoyMilk, name="doubleVeganPizzaWithSoyMilk"),
    path('lentilNutTacos/', views.lentilNutTacos, name="lentilNutTacos"),
    path('mushroomFriedRice/', views.mushroomFriedRice, name="mushroomFriedRice"),
    path('peanutRaisinOatmeal/', views.peanutRaisinOatmeal, name="peanutRaisinOatmeal"),
    path('penneArabiataWithSoyMilk/', views.penneArabiataWithSoyMilk, name="penneArabiataWithSoyMilk"),
    path('pumpkinPie/', views.pumpkinPie, name="pumpkinPie"),
    path('soyMilk/', views.soyMilk, name="soyMilk"),
    path('veganLasagnaRolls/', views.veganLasagnaRolls, name="veganLasagnaRolls"),
    path('veganPizzaWithSoyMilk/', views.veganPizzaWithSoyMilk, name="veganPizzaWithSoyMilk"),
    path('vegetableMeat/', views.vegetableMeat, name="vegetableMeat"),
    path('porkChopWithMashedPotatoes/', views.porkChopWithMashedPotatoes, name="porkChopWithMashedPotatoes"),
    path('cerealWithFruit/', views.cerealWithFruit, name="cerealWithFruit"),
    path('tunaCucumberWrap/', views.tunaCucumberWrap, name="tunaCucumberWrap"),
    path('scrambledEggs/', views.scrambledEggs, name="scrambledEggs"),
    path('bananaBread/', views.bananaBread, name="bananaBread"),
    path('caesarSalad/', views.caesarSalad, name="caesarSalad"),
    path('californiaRollSushi/', views.californiaRollSushi, name="californiaRollSushi"),
    path('greenSaladWithHoneyLemonChicken/', views.greenSaladWithHoneyLemonChicken, name="greenSaladWithHoneyLemonChicken"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('', views.index, name="index"),
    path('home/', views.home, name="home"),
    path('submit-constraints/', views.submit_constraints, name="submit-constraints"),
]

spoonfulofgoodness/urls.py
from django.contrib import admin
from django.urls import  path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('foodList/', include('foodList.urls')),
    path('foodRecommendation/', include('foodRecommendation.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class Planner_Form(forms.Form):
    select_attrs = {
        'class': 'form-control',
        'style': 'margin-bottom: 1rem;',
    }

    checkbox_attrs = {
        'class': 'form-check',
        'style': 'margin-bottom: 1rem;',
    }

    vegan_checkbox_attrs = {
        'class': 'form-check',
        'style': 'margin-bottom: 1rem;',
        'onclick': "uncheckAntiVegan()",
    }

    antivegan_checkbox_attrs = {
        'class': 'form-check',
        'style': 'margin-bottom: 1rem;',
        'onclick': "uncheckVegan()",
    }

    milk_checkbox_attrs = {
        'class': 'form-check',
        'style': 'margin-bottom: 1rem;',
        'onclick': "milkIsChecked()",
    }

    milk_substitute_checkbox_attrs = {
        'class': 'form-check',
        'style': 'margin-bottom: 1rem;',
        'onclick': "uncheckMilk()",
    }

    calories_choices = (
        ('Diet', 'Diet'),
        ('Normal', 'Normal'),
        ('High Calories', 'High Calories'),
    )

    meals_num_choices = (
        (2, 2),
        (3, 3),
        (4, 4),
    )

    milk_choices = (
        ('Milk', 'Milk'),
        ('Milk substitute', 'Milk substitute'),
    )

    boolean_choices = (
        (True, 'Yes'),
        (False, 'No'),
    )

    ''' <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
            Default checkbox
        </label>
    </div> '''

    calories = forms.ChoiceField(label = 'Calories', required=True, choices=calories_choices, widget = forms.Select(attrs=select_attrs))
    meals_per_day = forms.ChoiceField(label = 'Number of Meals per Day',required=True, choices=meals_num_choices, widget=forms.Select(attrs=select_attrs))
    milk = forms.ChoiceField(label= 'Which milk to include', required=True, choices=milk_choices, widget=forms.Select(attrs=select_attrs))
    contains_alcohol = forms.BooleanField(label= 'Include alcohol', required=False, widget=forms.CheckboxInput(attrs=checkbox_attrs))
    contains_gluten = forms.BooleanField(label= 'Include gluten', required=False, widget=forms.CheckboxInput(attrs=checkbox_attrs))
    contains_lactose = forms.BooleanField(label= 'Include lactose', required=False, widget=forms.CheckboxInput(attrs=checkbox_attrs))
    is_vegan = forms.BooleanField(label= 'Are you a vegan', required=False, widget=forms.CheckboxInput(attrs=vegan_checkbox_attrs))
    contains_egg = forms.BooleanField(label= 'Include eggs', required=False, widget=forms.CheckboxInput(attrs=antivegan_checkbox_attrs))
    contains_meat = forms.BooleanField(label= 'Include meat', required=False, widget=forms.CheckboxInput(attrs=antivegan_checkbox_attrs))
    contains_pork = forms.BooleanField(label= 'Include pork', required=False, widget=forms.CheckboxInput(attrs=antivegan_checkbox_attrs))
    contains_fish = forms.BooleanField(label= 'Include fish', required=False, widget=forms.CheckboxInput(attrs=antivegan_checkbox_attrs))
    

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .forms import Planner_Form
from foodList.models import Recipe
from foodRecommendation.views import food_recommendation

import requests
import json

form_response = {}
json_response = {}

def index(request):
    global json_response
    response = {}
    response['planner_form'] = Planner_Form
    response['has_submit_constraints_form'] = bool(json_response)
    if (bool(json_response)):
        # should do something with json_response first
        dict_of_recipes = get_recipes_from_json(json_response)
        json_response = {}
        if (dict_of_recipes == None):
            response["has_solution"] = False
        else:
            response["has_solution"] = True
        response["planned_recipes"] = dict_of_recipes
        print(response["planned_recipes"]) # debug
    print("Views complete.") # debug
    return render(request, 'homepage/templates/index.html', response)

def home(request):
    return HttpResponseRedirect(reverse('homepage:index'))

def submit_constraints(request):
    global form_response
    global json_response
    
    # create a form instance and populate it with data from the request:
    form = Planner_Form(request.POST or None)

    # check whether method is a POST and whether the form is valid
    if(request.method == 'POST' and form.is_valid()):
        print("Form accepted.") # debug
        form_response['calories'] = form.cleaned_data['calories']
        form_response['meals_per_day'] = form.cleaned_data['meals_per_day']
        form_response['contains_alcohol'] = form.cleaned_data['contains_alcohol']
        form_response['contains_gluten'] = form.cleaned_data['contains_gluten']
        form_response['contains_lactose'] = form.cleaned_data['contains_lactose']
        form_response['contains_egg'] = form.cleaned_data['contains_egg']
        form_response['contains_meat'] = form.cleaned_data['contains_meat']
        form_response['contains_pork'] = form.cleaned_data['contains_pork']
        form_response['contains_fish'] = form.cleaned_data['contains_fish'] 
        form_response['is_vegan'] = form.cleaned_data['is_vegan']
        form_response['contains_milk'] = form.cleaned_data['milk'] == "Milk"
        form_response['contains_milk_substitute'] = form.cleaned_data['milk'] == "Milk substitute"
        print(form_response) # debug
        
        json_response = get_json_of_food_recommendation(form_response)
        print(json_response) #debug
        form_response = {}
        return HttpResponseRedirect(reverse('homepage:index'))

    # if method is a GET (or any other method) or form is invalid, create a blank form
    else:
        print("Form not accepted.") # debug
        return HttpResponseRedirect(reverse('homepage:index'))

def get_json_of_food_recommendation(form_response):
    something = food_recommendation(form_response)
    print(something) #debug
    return JsonResponse(something, safe=False)

def get_recipes_from_json(json_response):
    '''
    Example of the json_response
    {
        "0": [{"recipeName": "lentilNutTacos", "recipeCalories": 740}, {"recipeName": "veganLasagnaRolls", "recipeCalories": 344}], 
        "1": [{"recipeName": "porkChopWithMashedPotatoes", "recipeCalories": 900}, {"recipeName": "carrotSticksWithDip", "recipeCalories": 350}], 
        "2": [{"recipeName": "lentilNutTacos", "recipeCalories": 740}, {"recipeName": "greenSaladWithHoneyLemonChicken", "recipeCalories": 380}], 
        "3": [{"recipeName": "porkChopWithMashedPotatoes", "recipeCalories": 900}, {"recipeName": "honeyLemonChicken", "recipeCalories": 320}], 
        "4": [{"recipeName": "porkChopWithMashedPotatoes", "recipeCalories": 900}, {"recipeName": "beefCutlet", "recipeCalories": 300}], 
        "5": [{"recipeName": "porkChopWithMashedPotatoes", "recipeCalories": 900}, {"recipeName": "caesarSalad", "recipeCalories": 230}], 
        "6": [{"recipeName": "porkChopWithMashedPotatoes", "recipeCalories": 900}, {"recipeName": "peanutRaisinOatmeal", "recipeCalories": 204}]
    }
    '''

    print(type(json_response.content)) #debug
    print(json_response.content) #debug
    json_response_content = json_response.content.decode("utf-8")
    data_from_json = json.loads(json_response_content)
    if (isinstance(data_from_json, dict)):
        recipe_dict = {} # dict with days as key and list of model object names as value

        dict_of_days = {
            "0": "Sunday",
            "1": "Monday",
            "2": "Tuesday",
            "3": "Wednesday",
            "4": "Thursday",
            "5": "Friday",
            "6": "Saturday",
        }
        

        for key in data_from_json.keys():
            day = dict_of_days[key]
            day_food_list = data_from_json[key] # list of dictionaries

            list_of_recipe_for_day = change_list_of_dictionaries_to_list_of_model_objects(day_food_list) # list of model object names
            
            recipe_dict[day] = list_of_recipe_for_day
    else:
        recipe_dict = None
        
    return recipe_dict

def change_list_of_dictionaries_to_list_of_model_objects(day_food_list):
    list_of_recipe_for_day = [] # list of model object names
    for dictio in day_food_list:
        recipe_object = (Recipe.objects.filter(recipeName = dictio["recipeName"]))[0].recipeName
        list_of_recipe_for_day.append(recipe_object)
    return list_of_recipe_for_day

homepage/templates/index.html
{% extends "spoonfulofgoodness/layout/base.html" %}
{% load static %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}" type="text/css">
    <script src="{% static 'js/homepage/planner-table.js' %}"></script>
{% endblock %}

{% block content %}

<!-- start banner Area -->
<section class="banner-area relative one-section" id="home">
    <div class="container">
        <div class="row fullscreen d-flex align-items-center justify-content-start">
            <div class="banner-content col-lg-8 col-md-12">
                <h4 class="text-white text-uppercase">Get Healthier Menus With</h4>
                <h1>
                    Spoonful of Goodness					
                </h1>
                <p class="text-white">
                    Do not bother yourself to worry about your nutrition limit.<br>Just state your needs and goals and we shall plan the best meals for you!
                </p>
                <a href="#planner" class="primary-btn header-btn text-uppercase">Make Your Plan</a>
            </div>												
        </div>
    </div>
</section>
<!-- End banner Area -->	

<!-- Start top-dish Area -->
<section class="top-dish-area section-gap one-section" id="dish">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-60 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10">Our Top Rated Dishes</h1>
                    <p>Who are in extremely love with eco friendly system.</p>
                </div>
            </div>
        </div>						
        <div class="row">
            <div class="single-dish col-lg-4">
                <div class="thumb">
                    <img class="img-fluid"  src="{% static 'img/d1.jpg' %}" alt="">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Bread Fruit Cheese Sandwich</h4>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>
            <div class="single-dish col-lg-4">
                <div class="thumb">
                    <img class="img-fluid"  src="{% static 'img/d2.jpg' %}" alt="">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Beef Cutlet with Spring Onion</h4>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>
            <div class="single-dish col-lg-4">
                <div class="thumb">
                    <img class="img-fluid"  src="{% static 'img/d3.jpg' %}" alt="">
                </div>
                <h4 class="text-uppercase pt-20 pb-20">Meat with sauce & Vegetables</h4>
                <p>
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct women face higher conduct.
                </p>
            </div>												
        </div>
    </div>	
</section>
<!-- End top-dish Area -->


<!-- Start features Area -->
<section class="features-area pt-100 one-section" id="feature">
    <div class="container">
        <div class="feature-section">
            <div class="row">
                <div class="single-feature col-lg-3 col-md-6">
                    <img src="{% static 'img/f1.png' %}" alt="">
                    <h4 class="pt-20 pb-20">Refreshing Breakfast</h4>
                </div>
                <div class="single-feature col-lg-3 col-md-6">
                    <img src="{% static 'img/f2.png' %}" alt="">
                    <h4 class="pt-20 pb-20">Awesome Lunch</h4>
                </div>
                <div class="single-feature col-lg-3 col-md-6">
                    <img src="{% static 'img/f3.png' %}" alt="">
                    <h4 class="pt-20 pb-20">Soothing Dinner</h4>
                </div>
                <div class="single-feature col-lg-3 col-md-6">
                    <img src="{% static 'img/f4.png' %}" alt="">
                    <h4 class="pt-20 pb-20">Rich Quality Buffet</h4>
                </div>														
            </div>											
        </div>
    </div>	
</section>
<!-- End features Area -->

<!-- start planner Area -->		
<section class="blog-area section-gap" id="planner">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10">Make Your Meal Plan</h1>
                    <p>Just enter your goal, needs, and restrictions. Let us make the plan for you.</p>
                </div>
            </div>
        </div>

        <form class="planner-form" method="POST" action="{% url 'homepage:submit-constraints' %}">
            {% csrf_token%}
            {{planner_form}}
            <button type="submit" class="btn btn-success" style="margin-bottom:2rem">Get Your Plan</button>
        </form>
        
        {% if has_submit_constraints_form %}
            <!-- Uses bootstrap's classes to create table -->
            <!-- Creates table by filling each column one by one, not filling per row.
            Source: https://stackoverflow.com/questions/16071864/how-to-create-tables-from-column-data-instead-of-row-data-in-html -->
            
            {% if has_solution %}
            <div class="table-responsive">
                <table>
                    <thead class="thead-light table table-hover">
                        <tr>
                            {% for item in planned_recipes %}
                                <th scope="col">{{item}}</th>
                            {% endfor %}
                        </tr>
                    </thead>

                    <tr>
                    {% for key, value in planned_recipes.items %}
                    <td>
                        <table class="table table-hover">
                            <tbody>
                                {% for recipeName in value %}
                                <tr>
                                    <td>
                                        <div class="card">
                                            <div class="card-body">
                                                <h5 class="card-title">{{recipeName}}</h5>
                                                <a href="#planner" onmouseover="getHrefForPlannerCardButton(this)" class="btn btn-primary check-it-out">Check it out!</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </td>
                    {% endfor %} 
                    </tr>
                </table>
            </div>
            {% else %}
            <div class="alert alert-danger" role="alert">
                    The combination of inputs you submit could not be planned.
            </div>
            {% endif %}
        
        {% endif %}
    </div>	
</section>
<!-- end planner Area -->

{% endblock %}

{% block javascript %}
    <script src="{% static 'js/homepage/constraints-form.js' %}"></script>
{% endblock %}